apiVersion: apps/v1
kind: Deployment
metadata:
  name: workorderclient-deployment
  labels:
    name: workorderclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workorderclient
  template:
    metadata:
      labels:
        app: workorderclient
    spec:
      containers:
      - name: workorderclient
        image: souviksardar/workorder-client:v1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development 
          - name: LaborAPIUrl
            valueFrom:
              configMapKeyRef:
                key: workorderapi__url
                name: workorderapi-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: workorderclient-service
spec:
  type: NodePort
  selector:
    app: workorderclient
  ports:
   - protocol: TCP
     port: 8001
     targetPort: 80
     nodePort: 32000